name: Ensure Filename of RFCs

on:
  pull_request:
    paths:
      - 'text/*.md'

jobs:
  check-filename:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get Changed Files
        uses: lots0logs/gh-action-get-changed-files@2.1.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Filter Added Files to Added RFCs
        id: files
        run: |
          added_files=`jq -r '[.[] | select(startswith("text/"))] | join(" ")' ${HOME}/files_added.json`
          echo "::set-output name=added::$added_files"

      - name: Checkout tools repo
        uses: actions/checkout@v2
        with:
          repository: emberjs/rfcs-tooling
          path: rfcs-tooling

      - uses: actions/setup-node@v2.1.2

      - run: yarn install
        working-directory: rfcs-tooling

      - name: Test RFC Filename matches PR Number that adds it
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: node check-filename-matches-pr.js $PR_NUMBER ${{ steps.files.outputs.added }}
        working-directory: rfcs-tooling
