name: Generate a JSON file of all frontmatter

on:
  push:
    branches: [ main, master ]
    paths:
      - 'text/*.md'

jobs:
  generate-rfc-frontmatter-data-artifact:
    name: 'Generate a JSON file of RFC status'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup RFCs tooling
        uses: ./.github/actions/setup-rfcs-tooling

      - name: Generate frontmatter data file
        run: |
          node rfcs-tooling/list-frontmatter.js text/*.md > rfc-data.json

      - uses: actions/upload-artifact@v3
        with:
          name: rfc-data
          path: rfc-data.json
          if-no-files-found: error
