name: github pages

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: '0.3.1'

      - name: Prepare files
        run: |
          if [ ! -d src ]; then
              mkdir src
          fi
          echo "[Introduction](introduction.md)\n" > src/SUMMARY.md
          for f in $(ls text/* | sort)
          do
              echo "- [$(basename $f ".md")]($(basename $f))" >> src/SUMMARY.md
              cp $f src
          done
          cp README.md src/introduction.md

      - name: Build mdBook
        run: mdbook build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book