name: Stage Advanced

on:
  push:
    branches: [master]

jobs:
  advance-stage:
    - uses: actions/checkout@v3

    - id: get_merged_pr
      uses: actions-ecosystem/action-get-merged-pull-request@v1.0.1

    - if: steps.get_merged_pr.outputs.labels
      env:
        LABELS: ${{ steps.get_merged_pr.outputs.labels }}
      run: |
        # TODO: We may need to check S-Proposed and S-Exploring for initial merges in case the
        # label doesn't get updated before merge. Alternatively, we should not allow merging without
        # the correct label.
        if echo $LABELS | grep "S-Accepted" -q; then
          current_stage=accepted
          next_stage=ready-for-release
        elif echo $LABELS | grep "S-Ready for Release" -q; then
          current_stage=ready-for-release
          next_stage=released
        elif echo $LABELS | grep "S-Released" -q; then
          current_stage=released
          next_stage=recommended
        fi

        # FIXME: This should be the number of the RFC itself, not the last PR.
        branch=advance-stage-${{ steps.get_merged_pr.outputs.number }}
        git checkout -b $branch

        # FIXME: We should actually do something here.
        git commit -m "Bump stage to $next_stage" --allow-empty

        git push origin $branch
        # FIXME: Actually make PR
